/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesScBenchRouteImport } from './routes/case-studies.sc-bench'
import { Route as CaseStudiesBuildRouteImport } from './routes/case-studies.build'
import { Route as CaseStudiesBenchceptionRouteImport } from './routes/case-studies.benchception'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesScBenchRoute = CaseStudiesScBenchRouteImport.update({
  id: '/case-studies/sc-bench',
  path: '/case-studies/sc-bench',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesBuildRoute = CaseStudiesBuildRouteImport.update({
  id: '/case-studies/build',
  path: '/case-studies/build',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesBenchceptionRoute = CaseStudiesBenchceptionRouteImport.update({
  id: '/case-studies/benchception',
  path: '/case-studies/benchception',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/environments': typeof EnvironmentsRoute
  '/privacy': typeof PrivacyRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/benchception': typeof CaseStudiesBenchceptionRoute
  '/case-studies/build': typeof CaseStudiesBuildRoute
  '/case-studies/sc-bench': typeof CaseStudiesScBenchRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/environments': typeof EnvironmentsRoute
  '/privacy': typeof PrivacyRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/benchception': typeof CaseStudiesBenchceptionRoute
  '/case-studies/build': typeof CaseStudiesBuildRoute
  '/case-studies/sc-bench': typeof CaseStudiesScBenchRoute
  '/case-studies': typeof CaseStudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/environments': typeof EnvironmentsRoute
  '/privacy': typeof PrivacyRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/benchception': typeof CaseStudiesBenchceptionRoute
  '/case-studies/build': typeof CaseStudiesBuildRoute
  '/case-studies/sc-bench': typeof CaseStudiesScBenchRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/environments'
    | '/privacy'
    | '/case-studies/$slug'
    | '/case-studies/benchception'
    | '/case-studies/build'
    | '/case-studies/sc-bench'
    | '/case-studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/environments'
    | '/privacy'
    | '/case-studies/$slug'
    | '/case-studies/benchception'
    | '/case-studies/build'
    | '/case-studies/sc-bench'
    | '/case-studies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/environments'
    | '/privacy'
    | '/case-studies/$slug'
    | '/case-studies/benchception'
    | '/case-studies/build'
    | '/case-studies/sc-bench'
    | '/case-studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EnvironmentsRoute: typeof EnvironmentsRoute
  PrivacyRoute: typeof PrivacyRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesBenchceptionRoute: typeof CaseStudiesBenchceptionRoute
  CaseStudiesBuildRoute: typeof CaseStudiesBuildRoute
  CaseStudiesScBenchRoute: typeof CaseStudiesScBenchRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/sc-bench': {
      id: '/case-studies/sc-bench'
      path: '/case-studies/sc-bench'
      fullPath: '/case-studies/sc-bench'
      preLoaderRoute: typeof CaseStudiesScBenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/build': {
      id: '/case-studies/build'
      path: '/case-studies/build'
      fullPath: '/case-studies/build'
      preLoaderRoute: typeof CaseStudiesBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/benchception': {
      id: '/case-studies/benchception'
      path: '/case-studies/benchception'
      fullPath: '/case-studies/benchception'
      preLoaderRoute: typeof CaseStudiesBenchceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  PrivacyRoute: PrivacyRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesBenchceptionRoute: CaseStudiesBenchceptionRoute,
  CaseStudiesBuildRoute: CaseStudiesBuildRoute,
  CaseStudiesScBenchRoute: CaseStudiesScBenchRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
